# Generated by Django 5.2 on 2026-10-05 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_resource_pdf_ref_alter_resource_video_ref'),
        ('enrollment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def crear_completions_de_matriculas_activas(apps, schema_editor):
        Enrollment = apps.get_model('enrollment', 'Enrollment')
        Module = apps.get_model('catalog', 'Module')
        ModuleCompletion = apps.get_model('enrollment', 'ModuleCompletion')
        for enrollment in Enrollment.objects.filter(active_access=True):
            for module in Module.objects.filter(course_id=enrollment.course_id):
                ModuleCompletion.objects.get_or_create(
                    enrollment_id=enrollment.id,
                    module_id=module.id,
                    defaults={'estado': 'pendiente'},
                )
    def noop_reverse(apps, schema_editor):
        pass

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'English')], max_length=5)),
                ('codigo', models.CharField(max_length=255, unique=True)),
                ('generado_en', models.DateTimeField()),
                ('s3_key', models.CharField(max_length=255)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='enrollment.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('notas_admin', models.TextField(blank=True, default='', null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_approvals', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_completions', to='enrollment.enrollment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='catalog.module')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'module'), name='unique_module_completion_enrollment_module')],
            },
        ),
        migrations.RunPython(crear_completions_de_matriculas_activas, noop_reverse),
    ]

    