# Generated by Django 5.2 on 2026-09-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_module_resource_i18n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Si está desmarcado, el alumno no lo ve en /curso/.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(help_text='Identificador en la URL. No cambia con el idioma.', unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, help_text='Solo define el orden de visualización. No bloquea módulos.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='pdf_ref',
            field=models.CharField(blank=True, help_text='Placeholder Semana 2. En Semana 3 será la key de S3.', max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='video_ref',
            field=models.CharField(blank=True, help_text='Placeholder Semana 2. En Semana 3 será el id/token de Bunny.', max_length=255),
        ),
    ]
