# Generated by Django 5.2 on 2026-10-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_course_is_published_alter_course_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='pdf_ref',
            field=models.CharField(blank=True, help_text='Key S3 del PDF base, p. ej. pdfs/jefes-a-punto/bienvenida/guia-1.pdf', max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='video_ref',
            field=models.CharField(blank=True, help_text='Video ID de Bunny Stream (UUID). Vacío o pending:// = sin player.', max_length=255),
        ),
    ]
